src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME', fields: ['username'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $username = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    /**
     * @var Collection<int, Orders>
     */
    #[ORM\OneToMany(targetEntity: Orders::class, mappedBy: 'manager')]
    private Collection $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * @return Collection<int, Orders>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setManager($this);
        }

        return $this;
    }

    public function removeOrder(Orders $order): static
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getManager() === $this) {
                $order->setManager(null);
            }
        }

        return $this;
    }
}

templates/components/badge.html.twig
{% set bgClass = '' %}

{% if name == 'En cours' %}
    {% set bgClass = 'bg-red-900 text-red-300' %}
{% elseif name == 'Prêt' %}
    {% set bgClass = 'bg-green-900 text-green-300' %}
{% else %}
    {% set bgClass = '' %}
{% endif %}

<span class="{{ bgClass }} ml-2 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full">{{ name }}</span>

templates/components/blankCard.html.twig
<a href="{{ path(url) }}">
  <div class="w-1/2 mx-auto text-center text-gray-500 dark:text-gray-400 border p-4 mt-12 cursor-pointer">
    <h3 class="mb-1 text-xl font-semibold tracking-tight text-gray-900 dark:text-white">{{ text }}</h3>
    <p class="font-light text-sm text-gray-500 dark:text-gray-400 flex justify-center items-center">
      <span class="flex-grow border-t border-gray-300 mx-2"></span> Voir plus <span class="flex-grow border-t border-gray-300 mx-2"></span>
    </p>
  </div>
</a>

templates/components/bookingNew.html.twig
<div id="popup-form-booking" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">
  <div class="relative p-4 w-full max-w-lg h-full md:h-auto">
      <div class="relative p-4 bg-white rounded-lg shadow dark:bg-gray-800 md:p-8">
          <div class="mb-4 text-sm font-light text-gray-500 dark:text-gray-400">
              <h3 class="mb-3 text-2xl font-bold text-gray-900 dark:text-white">Ajouter une réservation</h3>
          </div>
          <div class="justify-between items-center pt-0 space-y-4 sm:flex sm:space-y-0">
            {{ form_start(form) }}
                {{ form_row(form.name) }}
                {{ form_row(form.capacity) }}
                {{ form_row(form.location) }}
                {{ form_row(form.status) }}
                {{ form_row(form.nb) }}
                <div class="flex justify-end mt-4">
                    <button type="button" class="bg-gray-500 text-white px-4 py-2 rounded mr-2" id="cancel-button">Annuler</button>
                    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Ajouter</button>
                </div>
            {{ form_end(form) }}
          </div>
      </div>
  </div>
</div>

templates/components/cardTeam.html.twig
<div id="{{ person.id }}" class="text-center text-gray-500 dark:text-gray-400">
    <img class="mx-auto mb-4 w-36 h-36 rounded-full" src="/images/blank-profile-picture.webp" alt="Bonnie Avatar">
    <h3 class="mb-1 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ person.lastName }} {{ person.firstName }}</h3>
    <div class="flex flex-row justify-center" id="role-container-{{ person.id }}">
        <p class="mr-2 role-text">{{ person.roles[0] }}</p>
        <select id="role-input-{{ person.id }}" class="role-input hidden">
            <option value="Service" {% if person.roles[0] == 'Service' %}selected{% endif %}>Service</option>
            <option value="Bar" {% if person.roles[0] == 'Bar' %}selected{% endif %}>Bar</option>
            <option value="Cuisine" {% if person.roles[0] == 'Cuisine' %}selected{% endif %}>Cuisine</option>
            <option value="Repos" {% if person.roles[0] == 'Repos' %}selected{% endif %}>Repos</option>
        </select>
        <button class="save-role hidden" data-user-id="{{ person.id }}">
            <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.5 11.5 11 14l4-4m6 2a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
            </svg>
        </button>
        <svg class="w-6 h-6 text-gray-800 dark:text-white edit-role" data-user-id="{{ person.id }}" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.779 17.779 4.36 19.918 6.5 13.5m4.279 4.279 8.364-8.643a3.027 3.027 0 0 0-2.14-5.165 3.03 3.03 0 0 0-2.14.886L6.5 13.5m4.279 4.279L6.499 13.5m2.14 2.14 6.213-6.504M12.75 7.04 17 11.28"/>
        </svg>
    </div>

    <ul class="flex justify-evenly mt-4 w-1/2 m-auto">
        <li>
            <a href="#" class="text-[#39569c] hover:text-gray-900 dark:hover:text-white">
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M7.978 4a2.553 2.553 0 0 0-1.926.877C4.233 6.7 3.699 8.751 4.153 10.814c.44 1.995 1.778 3.893 3.456 5.572 1.68 1.679 3.577 3.018 5.57 3.459 2.062.456 4.115-.073 5.94-1.885a2.556 2.556 0 0 0 .001-3.861l-1.21-1.21a2.689 2.689 0 0 0-3.802 0l-.617.618a.806.806 0 0 1-1.14 0l-1.854-1.855a.807.807 0 0 1 0-1.14l.618-.62a2.692 2.692 0 0 0 0-3.803l-1.21-1.211A2.555 2.555 0 0 0 7.978 4Z"/>
                </svg>
            </a>
        </li>
        <li>
            <a href="#" class="text-[#00acee] hover:text-gray-900 dark:hover:text-white">
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M2.038 5.61A2.01 2.01 0 0 0 2 6v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6c0-.12-.01-.238-.03-.352l-.866.65-7.89 6.032a2 2 0 0 1-2.429 0L2.884 6.288l-.846-.677Z"/>
                    <path d="M20.677 4.117A1.996 1.996 0 0 0 20 4H4c-.225 0-.44.037-.642.105l.758.607L12 10.742 19.9 4.7l.777-.583Z"/>
                </svg>
            </a>
        </li>
    </ul>
</div>

templates/components/empty.html.twig
<div class="flex flex-col items-center justify-center mx-auto p-6 max-w-xs mt-12">
  <img src="/images/serveur.png" alt="{{ text }}" class="w-32 h-32 object-cover mb-4">
  <h2 class="text-2xl font-bold text-gray-700">{{ text }}</h2>
</div>

templates/components/menuNew.html.twig
<div id="popup-form-menu" class="fixed inset-0 bg-gray-600 bg-opacity-50 hidden flex items-center justify-center">
  <div class="bg-white p-6 rounded-lg shadow-lg">
      <h2 class="text-xl mb-4">Ajouter un Produit</h2>
      {{ form_start(form) }}
          {{ form_row(form.name) }}
          {{ form_row(form.type) }}
          {{ form_row(form.available) }}
          <div class="flex justify-end mt-4">
              <button type="button" class="bg-gray-500 text-white px-4 py-2 rounded mr-2" id="cancel-button">Annuler</button>
              <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Ajouter</button>
          </div>
      {{ form_end(form) }}
  </div>
</div>

templates/components/orderContent.html.twig
<div id="info-popup" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">
  <div class="relative p-4 w-full max-w-lg h-full md:h-auto">
      <div class="relative p-4 bg-white rounded-lg shadow dark:bg-gray-800 md:p-8">
          <div class="mb-4 text-sm font-light text-gray-500 dark:text-gray-400">
              <h3 class="mb-3 text-2xl font-bold text-gray-900 dark:text-white"></h3>
              <ul>
              </ul>
          </div>
          <div class="justify-between items-center pt-0 space-y-4 sm:flex sm:space-y-0">
              <div class="items-center space-y-4 sm:space-x-4 sm:flex sm:space-y-0">
                  <button id="close-modal" type="button"  class="py-2 px-4 w-full text-sm font-medium text-gray-500 bg-white rounded-lg border border-gray-200 sm:w-auto hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-primary-300 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">Cancel</button>
                  <div class="items-center space-y-4 sm:space-x-4 sm:flex sm:space-y-0">
                    <select id="status-select" class="py-2 px-4 w-full text-sm font-medium text-gray-500 bg-white rounded-lg border border-gray-200 sm:w-auto hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-primary-300 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">
                        <option value="En cours">En cours</option>
                        <option value="Prête">Prête</option>
                        <option value="Terminée">Terminée</option>
                    </select>
                    <button id="confirm-button" type="button" class="hidden py-2 px-4 w-full text-sm font-medium text-center text-white rounded-lg bg-primary-700 sm:w-auto hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Confirm</button>
                </div>
              </div>
          </div>
      </div>
  </div>
</div>